// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Dru
    {
        public int KeyNo { get; set; }
        public string Cvocable { get; set; }
        public string Evocable { get; set; }
        public byte[] Cmemo { get; set; }
        public byte[] Ememo { get; set; }
        public int? MedLink { get; set; }
        public int? Opelink { get; set; }
        public int? SurLink { get; set; }
        public int? RelationCount { get; set; }
        public int? UseLevel { get; set; }
        public bool? SkinInject { get; set; }
        public string Cxmlmemo { get; set; }
        public string Hkvocable { get; set; }
        public int Conid { get; set; }
        public string Hxmlmemo { get; set; }
        public int? MinV { get; set; }
        public int? MaxV { get; set; }
        public bool? Jy { get; set; }
    }
}