// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Gddru
    {
        public int? Ifid { get; set; }
        public int? Druconid { get; set; }
        public int? Fconid { get; set; }
        public string Druname { get; set; }
        public string Drutbl { get; set; }
        public bool? Isuse { get; set; }
        public string Drumemo { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public int Id { get; set; }
        public int Inx { get; set; }
        public int? DrukeyNo { get; set; }
    }
}