// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Gdfan
    {
        public int? Ifid { get; set; }
        public int? Fconid { get; set; }
        public string Fstr { get; set; }
        public string Ftbl { get; set; }
        public bool? Isuse { get; set; }
        public string Fanmemo { get; set; }
        public byte[] T1 { get; set; }
        public string T2 { get; set; }
        public int Id { get; set; }
        public int Inx { get; set; }
    }
}