// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Ifinfo
    {
        public int? Conid { get; set; }
        public string Tbl { get; set; }
        public int Ifid { get; set; }
        public string Ifstr { get; set; }
        public string Ifmemo { get; set; }
        public bool? Isuse { get; set; }
        public int? Ifno { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public int Inx { get; set; }
        public int Id { get; set; }
        public DateTime? Wrdate { get; set; }
        public int? Op { get; set; }
        public string Eng { get; set; }
    }
}