// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Ifstr
    {
        public string Atbl { get; set; }
        public string Btbl { get; set; }
        public int? AkeyNo { get; set; }
        public int? BkeyNo { get; set; }
        public string Acv { get; set; }
        public string Bcv { get; set; }
        public string Ifstr1 { get; set; }
        public DateTime? Wrdate { get; set; }
        public string Memo { get; set; }
        public int? Keyno { get; set; }
    }
}