// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Ill
    {
        public int KeyNo { get; set; }
        public string Cvocable { get; set; }
        public string Evocable { get; set; }
        public string Code { get; set; }
        public byte[] Cmemo { get; set; }
        public byte[] Ememo { get; set; }
        public byte[] Cadvice { get; set; }
        public byte[] Eadvice { get; set; }
        public string Symlink { get; set; }
        public string SymaddtionNum { get; set; }
        public int? MedLink { get; set; }
        public int? OpeLink { get; set; }
        public int? SurLink { get; set; }
        public int? HelLink { get; set; }
        public int? LabLink { get; set; }
        public int? NurLink { get; set; }
        public int? RelationCount { get; set; }
        public string Rright { get; set; }
        public byte[] Photo { get; set; }
        public int? UseLevel { get; set; }
        public string Cxmlmemo { get; set; }
        public bool? IsCill { get; set; }
        public bool? IsOften { get; set; }
        public bool? IsNotOften { get; set; }
        public bool? IsTeach { get; set; }
        public bool? IsBase { get; set; }
        public string MainDep { get; set; }
        public string OthDep { get; set; }
        public bool? IfOpen { get; set; }
        public string Hkvocable { get; set; }
        public int Conid { get; set; }
        public string HXmlmemo { get; set; }
        public bool? IsEme { get; set; }
        public string Nosymlink { get; set; }
        public int? Ischild { get; set; }
        public int? Isman { get; set; }
        public int? Iswoman { get; set; }
        public int? Isfool { get; set; }
        public string Smemo { get; set; }
        public string Xmlmemo { get; set; }
        public int? Isfz { get; set; }
        public int? Isrz { get; set; }
        public string Smemo1 { get; set; }
        public string Illtype { get; set; }
    }
}