// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public partial class Ope
    {
        public int KeyNo { get; set; }
        public string Cvocable { get; set; }
        public string Evocable { get; set; }
        public byte[] Cmemo { get; set; }
        public byte[] Ememo { get; set; }
        public int? IllLink { get; set; }
        public int? TreLink { get; set; }
        public int? DruLink { get; set; }
        public int? FmuLink { get; set; }
        public int? HerLink { get; set; }
        public int? AidLink { get; set; }
        public int? AnaLink { get; set; }
        public int? RelationCount { get; set; }
        public int? UseLevel { get; set; }
        public string Cxmlmemo { get; set; }
        public short? IsAcu { get; set; }
        public string Hkvocable { get; set; }
        public int Conid { get; set; }
        public string Hxmlmemo { get; set; }
    }
}